# Generated by Django 3.0.6 on 2020-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200531_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_image',
            field=models.ImageField(upload_to='backgrounds/2020/05/31'),
        ),
    ]
