# Generated by Django 3.0.6 on 2020-06-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200607_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
    ]
