# Generated by Django 3.0.6 on 2020-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_note_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_image',
            field=models.ImageField(upload_to='backgrounds/2020/06/13'),
        ),
    ]
